# Generated by Django 6.0.3 on 2026-04-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairconfig',
            name='alert_webhook_url',
        ),
    ]
