# Generated by Django 6.0.3 on 2026-07-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0007_exchangerate_is_synthetic_sourcequotausage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Cuota mensual"),
                            ("REINFORCEMENT", "Refuerzo anual"),
                            ("KEYS", "Entrega de llaves"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_due_date", models.DateField()),
                ("occurrence_count", models.PositiveIntegerField()),
                ("interval_months", models.PositiveSmallIntegerField()),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("applies_cub", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Serie de pagos",
                "verbose_name_plural": "Series de pagos",
                "ordering": ["first_due_date", "kind"],
            },
        ),
        migrations.CreateModel(
            name="CubIndexValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[("CUB_SC_STANDARD", "CUB-SC estándar")],
                        default="CUB_SC_STANDARD",
                        max_length=30,
                    ),
                ),
                ("reference_month", models.DateField()),
                ("applicable_month", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monthly_variation",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Valor CUB",
                "verbose_name_plural": "Valores CUB",
                "ordering": ["-applicable_month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series", "applicable_month"), name="unique_cub_series_month"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gt", 0)), name="cub_value_positive"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("applies_cub", models.BooleanField(default=True)),
                (
                    "locked_cub_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "adjusted_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "final_amount_override",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "locked_cub",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locked_obligations",
                        to="rates.cubindexvalue",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="rates.paymentseries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obligación de pago",
                "verbose_name_plural": "Obligaciones de pago",
                "ordering": ["due_date", "series__kind", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("paid_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="rates.paymentobligation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago realizado",
                "verbose_name_plural": "Pagos realizados",
                "ordering": ["-paid_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyPurchasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("contract_date", models.DateField()),
                ("currency", models.CharField(default="BRL", editable=False, max_length=3)),
                (
                    "cub_series",
                    models.CharField(
                        choices=[("CUB_SC_STANDARD", "CUB-SC estándar")],
                        default="CUB_SC_STANDARD",
                        max_length=30,
                    ),
                ),
                ("base_cub_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_cub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_for_plans",
                        to="rates.cubindexvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de vivienda",
                "verbose_name_plural": "Planes de vivienda",
                "ordering": ["archived_at", "name"],
            },
        ),
        migrations.AddField(
            model_name="paymentseries",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_series",
                to="rates.propertypurchaseplan",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentobligation",
            index=models.Index(fields=["due_date"], name="rates_payme_due_dat_561c45_idx"),
        ),
        migrations.AddConstraint(
            model_name="paymentobligation",
            constraint=models.UniqueConstraint(
                fields=("series", "sequence"), name="unique_obligation_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_amount__gt", 0)),
                name="payment_obligation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="payment_transaction_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentseries",
            constraint=models.UniqueConstraint(
                fields=("plan", "kind"), name="unique_payment_series_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence_count__gt", 0)),
                name="payment_series_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_months__gt", 0)),
                name="payment_series_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_amount__gt", 0)), name="payment_series_amount_positive"
            ),
        ),
    ]
