# Generated by Django 6.0.3 on 2026-07-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0009_paymentobligation_calculation_base_cub_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("DOWN_PAYMENT", "Entrada"),
                    ("MONTHLY", "Cuota mensual"),
                    ("REINFORCEMENT", "Refuerzo anual"),
                    ("KEYS", "Entrega de llaves"),
                ],
                max_length=20,
            ),
        ),
    ]
